### ISSUE TITLE
Normative references to unpublished docs.

### ISSUE THREAD

**Issue by dcdolson** [dcdolson/draft-dolson-sfc-hierarchical#4]
The document makes normative references to I-D.ietf-sfc-nsh and I-D.ietf-sfc-control-plane, which are not yet published.
If they are not published, need to rewrite sections.

**Comment by boucadair** [comment]
I suggest to maintain I-D.ietf-sfc-nsh as normative but remove  I-D.ietf-sfc-control-plane from that section. 
Please see my changes.

**Comment by dcdolson** [comment]
ok, sfc-control-plane is no longer normative.
